name: My commits workflow
on: [ push ]
jobs:
  cr_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Find Issue
        id: findIssue
        run: |
          echo "::set-output name=COUNT::`gh issue list --mention nizienko | grep \"My commits\" | wc -l`"
      - if: steps.findIssue.outputs.COUNT == 0
        run: |
          gh issue create --title "My commits" --body "@nizienko here is my commits"
      - if: steps.findIssue.outputs.COUNT > 0
        run: |
          gh issue comment ${{ISSUE}} --body "yet another push"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: gh issue list --mention nizienko | grep \"My commits\"
