name: My commits workflow
on: [ push ]
jobs:
  cr_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find Issue
        id: findIssue
        run: |
          echo "::set-output name=COUNT::`gh issue list | grep \"My issue\" |  wc -l`"
          gh issue list | grep "My issue"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - if: steps.findIssue.outputs.COUNT == 0
#        run: |
#          gh issue create --title "My commits" --body "@nizienko here is my commits"
#      - if: steps.findIssue.outputs.COUNT > 0
#        run: |
#          gh issue comment ${{steps.findIssue.outputs.ISSUE}} --body "yet another push"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
